import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import Filters from '../../components/Filters'
import ProductCard from '../../components/ProductCard'
import { IProduct } from '../../Models'
import { pages } from '../../Models/consts'
import styles from '../../styles/products.module.css'
import { BaseURL, EndPoints } from '../api/EndPoints'

type Props = {
  pageName: string;
  products: IProduct[];
}
const Products: NextPage<Props> = (props) => {
  const { products } = props;
  const [productsList, setproductsList] = useState(products);
  const [searchQuery, setSearchQuery] = useState('');

  const handleSearch = (query: string) => {
    setSearchQuery(query);
  }
  const handleFilter = (filter: string) => {
    setproductsList(products.filter(product => product.department === filter));
  }
  const handleClearFilter = () => {
    setproductsList(products);
  }

  return (
    <div>
      <Head>
        <title>Products [{products?.length | 0}]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container">
          <div className="row">

            <div className="col-12 col-md-9">
              <div className="container">
                <div className="row">
                  {productsList && productsList.length > 0 && productsList.map((product) => (
                    <ProductCard key={product.id} product={product} />
                  ))}
                </div>
              </div>
            </div>
            <div className="col-12 col-md-3">
              <Filters />
            </div>
          </div>
        </div>
      </main>
    </div>
  )


}
export async function getServerSideProps() {
  const res = await fetch(`${BaseURL}${EndPoints.products}`)
  const data = await res.json()

  return {
    props: {
      products: data || [],
      pageName: pages.products
    }
  }
}

export default Products
