import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Filters from '../../components/Filters'
import ProductCard from '../../components/ProductCard'
import { IProduct, IReview } from '../../Models'
import styles from '../../styles/products.module.css'
import { BaseURL, EndPoints } from '../api/EndPoints'

const Products: NextPage<{
  products: IProduct[]
}> = (props) => {
  const { products } = props;
  return (
    <div>
      <Head>
        <title>Products [{products?.length | 0}]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container">
          <div className="row">

            <div className="col-12 col-md-9">
              <div className="container">
                <div className="row">

                  {products && products.length > 0 && products.map((product) => (
                    <ProductCard key={product.id} product={product} />
                  ))}

                </div>
              </div>
            </div>
            <div className="col-12 col-md-3">
              <Filters />
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )


}
export async function getServerSideProps() {
  const res = await fetch(`${BaseURL}${EndPoints.products}`)
  const data = await res.json()

  return {
    props: {
      products: data || [],
      pageName: 'Products'
    }
  }
}

export default Products
